iex "iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex"
iex "choco install googlechrome"
iex "choco install 7zip.install"
iex "choco install skype"
iex "choco install git.install"
iex "choco install nodejs.install"
iex "choco install tortoisegit"
iex "choco install poshgit"
iex "choco install visualstudiocode"
iex "choco install conemu"
iex "choco install visualstudio2015community"
