iex "Set-ExecutionPolicy Unrestricted"
iex "iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex"
iex "choco install googlechrome -y"
iex "choco install 7zip.install -y"
iex "choco install skype -y"
iex "choco install git.install -y"
iex "choco install nodejs.install -y"
iex "choco install tortoisegit -y"
iex "choco install poshgit -y"
iex "choco install visualstudiocode -y"
iex "choco install conemu -y"
iex "choco install visualstudio2015community -y"
